### ISSUE TITLE
CDash v3.0.0 problem with displaying data from database

### ISSUE THREAD

**Issue by juraj67** [Kitware/CDash#1066]
Hi, I have som problems with displaying my dashboard after installing CDash v3.0.0. After creating a new project and testing, the test results and my project info do not appear on my panel.

This is my CDash user.php page:
![cdash3](https://user-images.githubusercontent.com/47740276/93332220-d044cb00-f821-11ea-9d4f-69c5465e0965.PNG)

Error in my log file:
`development.ERROR: SQLSTATE[HY000] [1049] Unknown database 'cdash' (SQL: select * from `user` where `id` = 1 limit 1) `

Using phpmyadmin I can see the test results and project info in my database. 

Any help would be nice

**Comment by zackgalbreath** [comment]
It looks to me that the frontend hasn't been generated correctly. What happens if you run `npm run dev` from the root of your CDash clone?

**Comment by juraj67** [comment]
Hi, results after running `npm run dev`:
```
98% after emitting SizeLimitsPlugin

 DONE  Compiled successfully in 24151ms                                                                                                                                                                                                                              9:49:38 AM

(node:7764) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/ects/srcBuild/opt/CDash/public/js/directives/**.js'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```
Results after using  `node --trace-warnings ...`:
```
internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module '/home/ects/srcBuild/opt/CDash/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```
In directory `CDash/public/js/directives/` I can see **.js** files. Changing permission on this dir did not help.

**Comment by zackgalbreath** [comment]
Thanks for sharing this error report. We'll take a closer look & let you know what we find.

**Comment by williamjallen** [comment]
The underlying code has changed quite a bit since this issue was posted so this is probably stale.  If you continue to see this problem, please create a new issue.
