### ISSUE TITLE
Some urls redirecting to local server name instead of fqdn

### ISSUE THREAD

**Issue by umar456** [Kitware/CDash#1084]
Some of the php redirects are forwarding to the local server name instead of the domain name of the server. For example the project image on this [page](https://ci.arrayfire.org/index.php?project=ArrayFire) is forwarding to https://cdash/image/1 instead of https://ci.arrayfire.org/image/1. This breaks the build pages and some images. I tried to debug this in the source code but I am not very familiar with php so I didn't make much progress.

I am using the official docker image.
```
$CDASH_CONFIG=$CDASH_DB_HOST = 'postgres_cdash2'; $CDASH_DB_NAME = 'xxx'; $CDASH_DB_TYPE = 'pgsql'; $CDASH_DB_LOGIN = 'xxx'; $CDASH_DB_PORT = ''; $CDASH_DB_PASS = 'xxxx'; $CDASH_DB_CONNECTION_TYPE = 'host'; $CDASH_BASE_URL= 'https://ci.arrayfire.org'; $CDASH_USE_HTTPS='1'; $CDASH_MAININDEX_TITLE = 'ArrayFire'; $CDASH_MAININDEX_SUBTITLE = 'Projects'; $CDASH_SERVER_NAME = 'ci.arrayfire.org'; $CDASH_PRODUCTION_MODE = true; $CDASH_EMAILADMIN = 'umar@arrayfire.com'; $CDASH_FORWARDING_IP = '172.%'; $CDASH_LOG_LEVEL = 'LOG_INFO';
```

**Comment by zackgalbreath** [comment]
I'll take a closer look to see if I can figure out what's going wrong & how to fix it.

In the meantime, if you want to fix this manually, shell into your docker container and set `APP_URL` in your .env file to be https://ci.arrayfire.org. After making that edit, run the `npm run dev` command.

**Comment by umar456** [comment]
I tried your suggestion but it did not make a difference. I applied your changes and:
1. check the site without a restart.
2. Restart the container
3. Reload apache after making the changes

All tests were done by first disabling the cache on my browser.

**Comment by zackgalbreath** [comment]
Thanks for trying that. I'll take a closer look & let you know what I discover.

**Comment by umar456** [comment]
Hey @zackgalbreath Any updates on this?

Debugged a bit today. The `npm run dev` command runs fine but I am running in production mode (at least thats what I am assuming since the `CDASH_PRODUCTION_MODE` is set to true). When I ran `npm dev prod` I got the following error:

```
 ERROR  Failed to compile with 2 errors                                                                                                                                                                                                                                                                                                                                             7:20:06 PM

 error  in ./resources/sass/app.scss

Syntax Error: ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(259:4) Unclosed block

  257 | 
  258 |   .navbar-toggler-icon {
> 259 |     background-image: escape-svg($navbar-light-toggler-icon-bg);
      |    ^
  260 |   }
  261 | 


 error  in ./resources/sass/app.scss

Syntax Error: SyntaxError

(259:4) Unclosed block

  257 | 
  258 |   .navbar-toggler-icon {
> 259 |     background-image: escape-svg($navbar-light-toggler-icon-bg);
      |    ^
  260 |   }
  261 | 



 @ ./resources/sass/app.scss 2:14-253

                                                      Asset       Size  Chunks             Chunk Names
                                    /build/css/3rdparty.css    222 KiB          [emitted]  
                         /build/css/cdash_1611602387253.css   1.01 KiB          [emitted]  
                    /build/css/colorblind_1611602387253.css  890 bytes          [emitted]  
                                      /build/css/common.css   25.6 KiB          [emitted]  
                          /build/views/buildProperties.html   9.57 KiB          [emitted]  
                          /build/views/compareCoverage.html   6.46 KiB          [emitted]  
                                    /build/views/index.html   22.7 KiB          [emitted]  
                         /build/views/manageBuildGroup.html     18 KiB          [emitted]  
                       /build/views/manageMeasurements.html   3.86 KiB          [emitted]  
                           /build/views/manageOverview.html   4.67 KiB          [emitted]  
                         /build/views/manageSubProject.html   11.5 KiB          [emitted]  
                                 /build/views/overview.html   6.23 KiB          [emitted]  
        /build/views/partials/buildError_1611602387253.html   4.05 KiB          [emitted]  
             /build/views/partials/build_1611602387253.html   15.2 KiB          [emitted]  
        /build/views/partials/buildgroup_1611602387253.html   10.4 KiB          [emitted]  
         /build/views/partials/daterange_1611602387253.html  194 bytes          [emitted]  
     /build/views/partials/filterButtons_1611602387253.html  631 bytes          [emitted]  
         /build/views/partials/filterRow_1611602387253.html   1.35 KiB          [emitted]  
/build/views/partials/filterdataTemplate_1611602387253.html   2.86 KiB          [emitted]  
            /build/views/partials/footer_1611602387253.html   1.47 KiB          [emitted]  
            /build/views/partials/header_1611602387253.html   6.49 KiB          [emitted]  
            /build/views/partials/logout_1611602387253.html  384 bytes          [emitted]  
   /build/views/partials/subProjectTable_1611602387253.html    8.6 KiB          [emitted]  
          /build/views/partials/timeline_1611602387253.html  585 bytes          [emitted]  
      /build/views/partials/updatedfiles_1611602387253.html   2.04 KiB          [emitted]  
                               /build/views/queryTests.html   7.35 KiB          [emitted]  
                             /build/views/testOverview.html   7.13 KiB          [emitted]  
                              /build/views/testSummary.html   5.85 KiB          [emitted]  
                                     /build/views/user.html   16.4 KiB          [emitted]  
                           /build/views/userStatistics.html   6.58 KiB          [emitted]  
                           /build/views/viewBuildError.html   4.86 KiB          [emitted]  
                      /build/views/viewDynamicAnalysis.html   2.55 KiB          [emitted]  
                  /build/views/viewDynamicAnalysisFile.html   1.82 KiB          [emitted]  
                             /build/views/viewProjects.html   4.13 KiB          [emitted]  
                          /build/views/viewSubProjects.html   7.17 KiB          [emitted]  
                                 /build/views/viewTest.html   12.9 KiB          [emitted]  
                               /build/views/viewUpdate.html   2.36 KiB          [emitted]  
                                        /js/1stparty.min.js   56.8 KiB          [emitted]  
                                        /js/3rdparty.min.js   1.45 MiB          [emitted]  
                             /js/CDash_1611602387253.min.js   1.51 MiB          [emitted]  
                                                   /main.js   1.02 KiB          [emitted]  
 + 2 hidden assets

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(259:4) Unclosed block

  257 | 
  258 |   .navbar-toggler-icon {
> 259 |     background-image: escape-svg($navbar-light-toggler-icon-bg);
      |    ^
  260 |   }
  261 | 

    at /home/kitware/cdash/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/kitware/cdash/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/kitware/cdash/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/kitware/cdash/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/kitware/cdash/node_modules/postcss-loader/src/index.js:207:9
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/dist/cjs.js??ref--5-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(259:4) Unclosed block

  257 | 
  258 |   .navbar-toggler-icon {
> 259 |     background-image: escape-svg($navbar-light-toggler-icon-bg);
      |    ^
  260 |   }
  261 | 

 @ ./resources/sass/app.scss 2:14-253
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cdash@3.0.2 production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cdash@3.0.2 production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-25T19_21_05_875Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cdash@3.0.2 prod: `npm run production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cdash@3.0.2 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-25T19_21_05_913Z-debug.log
```

Hope that helps.

**Comment by umar456** [comment]
Looks like setting the ASSET_URL and running `npm run dev` works.

**Comment by williamjallen** [comment]
#1454 resolved the issues with `npm run prod` so I believe this issue is now complete.  Please open a new issue or comment here if you continue to experience problems.
