### ISSUE TITLE
swiftmailer gets "550 5.7.1 Relaying denied" when registering new user (LDAP configuration)

### ISSUE THREAD

**Issue by seanm** [Kitware/CDash#1147]
With CDash 3.0.3, when I'm at:

https://cdash.example.com/manageProjectRoles.php?projectid=3#fragment-3

to "register a new user" I fill in the fields and press "Register User" and then I get a 500 error. This is the screen I'm referring to:

![CDash-relaying-denied](https://user-images.githubusercontent.com/117260/117357877-79a90180-ae83-11eb-8954-55ec3933312b.png)

Looking in the server logs I find the error message:

```
[2021-05-06 14:30:45] development.ERROR: Expected response code 250 but got code "550", with message "550 5.7.1 Relaying denied
" {"userId":1,"exception":"[object] (Swift_TransportException(code: 550): Expected response code 250 but got code \"550\", with message \"550 5.7.1 Relaying denied
\" at /usr/local/etc/apache24/cdash.example.com/CDash/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:460)
[stacktrace]
#0 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(345): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#2 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(393): Swift_Transport_EsmtpTransport->executeCommand()
#3 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(500): Swift_Transport_AbstractSmtpTransport->doDataCommand()
#4 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(519): Swift_Transport_AbstractSmtpTransport->doMailTransaction()
#5 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()
#6 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send()
#7 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(488): Swift_Mailer->send()
#8 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(261): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#9 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(185): Illuminate\\Mail\\Mailer->send()
#10 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Mail\\Mailer->raw()
#11 /usr/local/etc/apache24/cdash.example.com/CDash/app/cdash/include/cdashmail.php(79): Illuminate\\Support\\Facades\\Facade::__callStatic()
#12 /usr/local/etc/apache24/cdash.example.com/CDash/app/cdash/public/manageProjectRoles.php(188): cdashmail()
#13 /usr/local/etc/apache24/cdash.example.com/CDash/app/cdash/public/manageProjectRoles.php(246): register_user()
#14 /usr/local/etc/apache24/cdash.example.com/CDash/app/Http/Controllers/CDash.php(161): require('/usr/local/etc/...')
#15 /usr/local/etc/apache24/cdash.example.com/CDash/app/Http/Controllers/CDash.php(261): App\\Http\\Controllers\\CDash->getRequestContents()
#16 /usr/local/etc/apache24/cdash.example.com/CDash/app/Http/Controllers/CDash.php(60): App\\Http\\Controllers\\CDash->handleRequest()
#17 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\CDash->__invoke()
#18 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#19 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#20 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#21 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#22 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#23 /usr/local/etc/apache24/cdash.example.com/CDash/app/Http/Middleware/CheckPassword.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckPassword->handle()
#25 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#27 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#29 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#31 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#33 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#35 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#37 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#39 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#40 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#41 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#42 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#43 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#44 /usr/local/etc/apache24/cdash.example.com/CDash/app/Http/Middleware/CheckDirectoryPermissions.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDirectoryPermissions->handle()
#46 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#48 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#52 /usr/local/etc/apache24/cdash.example.com/CDash/app/Http/Middleware/CheckDatabaseConnection.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDatabaseConnection->handle()
#54 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#56 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#58 /usr/local/etc/apache24/cdash.example.com/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#59 /usr/local/etc/apache24/cdash.example.com/CDash/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#60 {main}
"} 
```

It looks like it's failing to send email.  Surprising since CDash *is* sending me daily emails for build warnings and test failures.  So it knows how to talk to my email server elsewhere.

If it matters, I'm using CDash with LDAP.

I don't recall ever having this ussue with CDash 2.6.

**Comment by williamjallen** [comment]
This relevant bits of the codebase have changed substantially since this issue was posted and I suspect that this has been resolved.  Please post a new issue if this is still occurring with a recent version of CDash.
