### ISSUE TITLE
Unable to connect mysql when installation

### ISSUE THREAD

**Issue by RenDongge** [Kitware/CDash#1204]
Hello.
I used docker image kitware/CDash.
![image](https://user-images.githubusercontent.com/45281610/148508910-58dc1439-186f-4e79-8fa2-8fd24eff8250.png)
In this page, I input a password and click install.
the page jump here
![image](https://user-images.githubusercontent.com/45281610/148509097-0da76ef3-1e8f-4539-8ed1-105e91594473.png)

the logcats in docker are as follow.

`development.ERROR: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /home/kitware/cdash/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /home/kitware/cdash/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /home/kitware/cdash/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)

[stacktrace]

#0 /home/kitware/cdash/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): Doctrine\\DBAL\\Driver\\PDO\\Exception::new(Object(PDOException))

#1 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=mysq...', 'root', '', Array)

#2 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(100): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=mysq...', 'root', '', Array)

#3 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(50): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'mysql:host=mysq...', 'root', '', Array)

#4 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=mysq...', Array, Array)

#5 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)

#6 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()

#7 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func(Object(Closure))

#8 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(349): Illuminate\\Database\\Connection->getPdo()

#9 /home/kitware/cdash/app/cdash/include/CDash/Database.php(45): Illuminate\\Database\\DatabaseManager->__call('getPdo', Array)

#10 /home/kitware/cdash/app/cdash/include/CDash/Database.php(110): CDash\\Database->getPdo()

#11 /home/kitware/cdash/app/cdash/include/pdo.php(279): CDash\\Database->query('\

SET SQL_MODE=\"...')

#12 /home/kitware/cdash/app/cdash/public/install.php(191): pdo_query('\

SET SQL_MODE=\"...')

#13 /home/kitware/cdash/app/cdash/public/install.php(204): _processSQLfile('/home/kitware/c...')

#14 /home/kitware/cdash/app/Http/Controllers/CDash.php(161): require('/home/kitware/c...')

#15 /home/kitware/cdash/app/Http/Controllers/CDash.php(261): App\\Http\\Controllers\\CDash->getRequestContents()

#16 /home/kitware/cdash/app/Http/Controllers/CDash.php(60): App\\Http\\Controllers\\CDash->handleRequest()

#17 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\CDash->__invoke('install.php')

#18 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('__invoke', Array)

#19 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\CDash), '__invoke')

#20 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()

#21 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()

#22 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))

#23 /home/kitware/cdash/app/Http/Middleware/CheckPassword.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#24 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckPassword->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#25 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#26 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#27 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#28 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#29 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#30 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#31 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#32 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#33 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#34 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#35 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#36 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#37 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#38 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))

#39 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))

#40 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))

#41 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))

#42 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))

#43 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))

#44 /home/kitware/cdash/app/Http/Middleware/CheckDirectoryPermissions.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#45 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDirectoryPermissions->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#46 /home/kitware/cdash/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#47 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#48 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#49 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#50 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#51 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#52 /home/kitware/cdash/app/Http/Middleware/CheckDatabaseConnection.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#53 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDatabaseConnection->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#54 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#55 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))

#56 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

#57 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))

#58 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))

#59 /home/kitware/cdash/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))

#60 {main}`
how can I solve it.

**Comment by williamjallen** [comment]
Closing this issue now since the Docker install process has changed significantly since this issue was posted.  Please create a new issue if you continue to experience problems with your installation with the latest version of CDash.
