### ISSUE TITLE
Exception in AddLine when submitting coverage

### ISSUE THREAD

**Issue by estan** [Kitware/CDash#1205]
Trying to upgrade our CDash from 2.6.0 to Git master (and switch to docker-compose deployment), but when our builds submit coverage info, we're getting this exception thrown:

```
cdash    | [2022-01-09 17:38:51] development.ERROR: A non well formed numeric value encountered {"exception":"[object] (ErrorException(code: 0): A non well formed numeric value encountered at /home/kitware/cdash/app/cdash/app/Model/CoverageFileLog.php:42)
cdash    | [stacktrace]
cdash    | #0 /home/kitware/cdash/app/cdash/app/Model/CoverageFileLog.php(42): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'A non well form...', '/home/kitware/c...', 42, Array)
cdash    | #1 /home/kitware/cdash/app/cdash/app/Model/CoverageFileLog.php(173): CDash\\Model\\CoverageFileLog->AddLine('141', '4')
cdash    | #2 /home/kitware/cdash/app/cdash/app/Model/CoverageFileLog.php(72): CDash\\Model\\CoverageFileLog->Load(true)
cdash    | #3 /home/kitware/cdash/app/cdash/xml_handlers/GcovTar_handler.php(375): CDash\\Model\\CoverageFileLog->Insert(true)
cdash    | #4 /home/kitware/cdash/app/cdash/xml_handlers/GcovTar_handler.php(135): GCovTarHandler->ParseGcovFile(Object(SplFileInfo))
cdash    | #5 /home/kitware/cdash/app/cdash/include/ctestparser.php(264): GCovTarHandler->Parse('/home/kitware/c...')
cdash    | #6 /home/kitware/cdash/app/cdash/include/ctestparser.php(285): parse_put_submission(Resource id #506, '1', '188c42ca1c531b5...')
cdash    | #7 /home/kitware/cdash/app/cdash/include/do_submit.php(143): ctest_parse(Resource id #506, '1', NULL, '188c42ca1c531b5...', false)
cdash    | #8 /home/kitware/cdash/app/cdash/include/do_submit.php(557): do_submit(Resource id #506, '1', NULL, '188c42ca1c531b5...', false)
cdash    | #9 /home/kitware/cdash/app/cdash/public/submit.php(58): put_submit_file()
cdash    | #10 /home/kitware/cdash/app/Http/Controllers/CDash.php(161): require('/home/kitware/c...')
cdash    | #11 /home/kitware/cdash/app/Http/Controllers/CDash.php(217): App\\Http\\Controllers\\CDash->getRequestContents()
cdash    | #12 /home/kitware/cdash/app/Http/Controllers/CDash.php(56): App\\Http\\Controllers\\CDash->handleSubmission()
cdash    | #13 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\CDash->__invoke('submit.php')
cdash    | #14 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('__invoke', Array)
cdash    | #15 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\CDash), '__invoke')
cdash    | #16 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
cdash    | #17 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
cdash    | #18 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #19 /home/kitware/cdash/app/Http/Middleware/CheckPassword.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #20 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckPassword->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #21 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #22 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #23 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #24 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #25 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #26 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #27 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #28 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #29 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #30 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #31 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #32 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #33 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #34 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
cdash    | #35 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
cdash    | #36 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
cdash    | #37 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
cdash    | #38 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
cdash    | #39 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #40 /home/kitware/cdash/app/Http/Middleware/CheckDirectoryPermissions.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #41 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDirectoryPermissions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #42 /home/kitware/cdash/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #43 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #44 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #45 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #46 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #47 /home/kitware/
cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #48 /home/kitware/cdash/app/Http/Middleware/CheckDatabaseConnection.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #49 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDatabaseConnection->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #50 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #51 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
cdash    | #52 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
cdash    | #53 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
cdash    | #54 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
cdash    | #55 /home/kitware/cdash/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
cdash    | #56 {main}
```
I'm guessing it is because AddLine is being fed the line number and count as a string here?

We're using CMake 3.16.3 from Ubuntu 20.04 packages.

**Comment by estan** [comment]
The output we're getting in our build job is:

```
No response from server.
Found bundle for host cdash.orexplore.se: 0x563f07e8f970 [serially]
Can not multiplex, even if we wanted to!
Re-using existing connection! (#0) with host cdash.orexplore.se
Connected to cdash.orexplore.se (192.168.1.15) port 443 (#0)
PUT /submit.php?type=GcovTar&md5=188c42ca1c531b5c17724ec26fdcdaa6&filename=gcov.tar&buildid=1 HTTP/1.1
Host: cdash.orexplore.se
Accept: */*
Content-Type: text/xml
Content-Length: 1882637
Expect: 100-continue
Mark bundle as not supporting multiuse
HTTP/1.1 100 Continue
program finished with exit code 255
elapsedTime=253.276832
BZh91AY&SY�error uploading to CDash. /buildbot/b-insight-test/build/../insight-build-ctest/gcov.tar https://cdash.orexplore.se/submit.php type=GcovTar&md5=188c42ca1c531b5c17724ec26fdcdaa6&filename=gcov.tar&buildid=1
```

**Comment by estan** [comment]
(I should note, the submission looks OK on the CDash webpage though, including coverage, it's just that the submission exits with status 255 and the messages above, which fails the build)

**Comment by estan** [comment]
I just tried with

```diff
diff --git a/app/cdash/app/Model/CoverageFileLog.php b/app/cdash/app/Model/CoverageFileLog.php
index 394fc54d1..63e640d27 100644
--- a/app/cdash/app/Model/CoverageFileLog.php
+++ b/app/cdash/app/Model/CoverageFileLog.php
@@ -39,9 +39,9 @@ class CoverageFileLog
     public function AddLine($number, $code)
     {
         if (array_key_exists($number, $this->Lines)) {
-            $this->Lines[$number] += $code;
+            $this->Lines[$number] += (int)$code;
         } else {
-            $this->Lines[$number] = $code;
+            $this->Lines[$number] = (int)$code;
         }
     }

```

and submissions now succeed:

```
cdash    | 172.26.0.1 - - [09/Jan/2022:19:33:03 +0000] "PUT /submit.php?type=GcovTar&md5=13ae0b17aec9355ea5035b0d60daa178&filename=gcov.tar&buildid=2 HTTP/1.1" 200 1148
```

Let me know if you want this as a PR, or if the fix should be something else.

**Comment by zackgalbreath** [comment]
Sorry for the slow reply. Sure, this change looks reasonable to me. If you create a PR of it I'll take a look & merge.
