### ISSUE TITLE
Project isn't listed when trying to manage project groups

### ISSUE THREAD

**Issue by vlebourl** [Kitware/CDash#1291]
When trying to manage the groups in my project, I only get a blank screen...
![image](https://user-images.githubusercontent.com/5701372/217237538-470d52e6-5f3d-4838-98b6-ee2e80ccb74e.png)

Here's the corresponding log error:
```
[2023-02-07 12:50:10] development.ERROR: Trying to access array offset on value of type bool {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type bool at /usr/share/CDash/app/cdash/app/Model/Site.php:240)
[stacktrace]
#0 /usr/share/CDash/app/cdash/app/Model/Site.php(240): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /usr/share/CDash/app/cdash/app/Model/Site.php(219): CDash\\Model\\Site->Fill()
#2 /usr/share/CDash/app/cdash/public/api/v1/manageBuildGroup.php(185): CDash\\Model\\Site->GetName()
#3 /usr/share/CDash/app/Http/Controllers/CDash.php(164): require('/usr/share/CDas...')
#4 /usr/share/CDash/app/Http/Controllers/CDash.php(182): App\\Http\\Controllers\\CDash->getRequestContents()
#5 /usr/share/CDash/app/Http/Controllers/CDash.php(55): App\\Http\\Controllers\\CDash->handleApiRequest()
#6 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\CDash->__invoke()
#7 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#8 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#10 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#11 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 /usr/share/CDash/app/Http/Middleware/CheckPassword.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckPassword->handle()
#14 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#16 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#18 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#20 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#22 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#24 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#26 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#28 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#30 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#32 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /usr/share/CDash/app/Http/Middleware/CheckDirectoryPermissions.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDirectoryPermissions->handle()
#35 /usr/share/CDash/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#37 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#41 /usr/share/CDash/app/Http/Middleware/CheckDatabaseConnection.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDatabaseConnection->handle()
#43 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#45 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#47 /usr/share/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#48 /usr/share/CDash/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#49 {main}
"}
```

**Comment by vlebourl** [comment]
I reinstalled everything and i can access my project... No idea how to reproduce this, so I'll close it.

**Comment by vlebourl** [comment]
Reproduce on a new project: 
- create a new BuildGroup
- go to Wildcard BuildGroups tab
- define Wildcard rule for the new group
- add "RPM" to Build Names should contain field
- select Continuous in Build Type field
- click Define BuildGroup.

Going back to the manageBuildGroup.php?prokectid=1 doesn't show anything anymore...

I'm using v3.1.0 installed through npm install && npm run dev.
Any help would be greatly appriciated!

**Comment by zackgalbreath** [comment]
This feature seems to be working okay for me locally. Here's what I did.

1. Create a new "Daily" buildgroup. I named my "wild". After clicking the "Create BuildGroup" button, you should see it listed on the "Current BuildGroups" tab or if you refresh `manageBuildGroup.php`.
2. On the "Wildcard BuildGroups" tab, I defined a rule:
  * *Define Wildcard rule for*: **wild** (the new Daily buildgroup I just created)
  * *Build Names should contain*: **wild** (this can be any string you want)
  * *Build Type*: **Experimental**
3. I then submitted a build using a ctest -S like the one pasted below
4. This build showed up in my new "wild" group, not the default Experimental" group.

```cmake
set(CTEST_SITE "hesperides.kitware")
set(CTEST_BUILD_NAME "wild")
set(CTEST_SOURCE_DIRECTORY ${CTEST_SCRIPT_DIRECTORY}/src)
set(CTEST_BINARY_DIRECTORY ${CTEST_SCRIPT_DIRECTORY}/bin)
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_NOTES_FILES "${CTEST_SCRIPT_DIRECTORY}/${CTEST_SCRIPT_NAME}")

ctest_empty_binary_directory("${CTEST_BINARY_DIRECTORY}")

ctest_start(Experimental)
ctest_configure()
ctest_build()
ctest_test()
ctest_submit()
```

<img width="1537" alt="Screen Shot 2023-02-07 at 2 19 56 PM" src="https://user-images.githubusercontent.com/224720/217344108-00aba896-a616-408b-802b-fda8aed18baa.png">

**Comment by vlebourl** [comment]
I have to admit I didn't even try to submit a new build as the group page became unavailable as soon as I created the wildcard...
