### ISSUE TITLE
Error 'MODULE_NOT_FOUND' at a fresh install

### ISSUE THREAD

**Issue by Scanframe** [Kitware/CDash#1298]
* [Reported Error](#reported-error)
* [Question](#question)
* [Versions](#versions)

## Reported Error

When running the last step of a fresh install using `npm run dev` the result with error is:

```
> cdash@3.1.0 dev
> npm run development


> cdash@3.1.0 development
> mix

[webpack-cli] Error: Cannot find module './src/table'
Require stack:
- /var/www/cdash/node_modules/cli-table3/index.js
- /var/www/cdash/node_modules/laravel-mix/src/webpackPlugins/BuildOutputPlugin.js
- /var/www/cdash/node_modules/laravel-mix/src/builder/webpack-plugins.js
- /var/www/cdash/node_modules/laravel-mix/src/builder/WebpackConfig.js
- /var/www/cdash/node_modules/laravel-mix/src/Mix.js
- /var/www/cdash/node_modules/laravel-mix/setup/webpack.config.js
- /var/www/cdash/node_modules/webpack-cli/lib/webpack-cli.js
- /var/www/cdash/node_modules/webpack-cli/lib/bootstrap.js
- /var/www/cdash/node_modules/webpack-cli/bin/cli.js
- /var/www/cdash/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/cdash/node_modules/cli-table3/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/cdash/node_modules/cli-table3/index.js',
    '/var/www/cdash/node_modules/laravel-mix/src/webpackPlugins/BuildOutputPlugin.js',
    '/var/www/cdash/node_modules/laravel-mix/src/builder/webpack-plugins.js',
    '/var/www/cdash/node_modules/laravel-mix/src/builder/WebpackConfig.js',
    '/var/www/cdash/node_modules/laravel-mix/src/Mix.js',
    '/var/www/cdash/node_modules/laravel-mix/setup/webpack.config.js',
    '/var/www/cdash/node_modules/webpack-cli/lib/webpack-cli.js',
    '/var/www/cdash/node_modules/webpack-cli/lib/bootstrap.js',
    '/var/www/cdash/node_modules/webpack-cli/bin/cli.js',
    '/var/www/cdash/node_modules/webpack/bin/webpack.js'
  ]
}
```

## Question

What am I doing wrong?

## Versions
Versions used for this install.

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

php -v
PHP 8.1.2-1ubuntu2.10 (cli) (built: Jan 16 2023 15:19:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.10, Copyright (c), by Zend Technologies

mysql --version
mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))

node --version
v12.22.9

npm --version
8.5.1

git remote -v
origin  https://github.com/Kitware/CDash (fetch)
origin  https://github.com/Kitware/CDash (push)

git branch -v
* master 45086af Merge pull request #1297 from Kitware/fix_style

```

**Comment by zackgalbreath** [comment]
Thanks for taking the time to write such a detailed error report. I'm having trouble reproducing this issue using the same version of Ubuntu and npm. Can you try the following steps & let us know how it goes?

```bash
cd /path/to/CDash
rm -r node_modules
npm install
npm run dev
```

**Comment by Scanframe** [comment]
> Thanks for taking the time to write such a detailed error report. I'm having trouble reproducing this issue using the same version of Ubuntu and npm. Can you try the following steps & let us know how it goes?
> 
> ```shell
> cd /path/to/CDash
> rm -r node_modules
> npm install
> npm run dev
> ```

Thanks.
Deleting directory "node_modules" did the trick to run `npm run dev` without errors.

The install manual does not explicitly tell which `/path/to/CDash/public/` or `/path/to/CDash/app/cdash/public` to use to configure for the webserver.
Maybe for some it is clear but not to me :)

**Comment by williamjallen** [comment]
A substantial portion of our build process has changed since this issue was filed.  Please feel free to file a new issue if you continue to experience problems with the latest version of CDash.
