### ISSUE TITLE
CDash server responding with `Error parsing XML in stream at line 1: syntax error` for Coverage XML

### ISSUE THREAD

**Issue by tamuseanmiller** [Kitware/CDash#1390]
I'm hoping this is a CDash issue and not a CMake/CTest issue but let me know. After calling my dashboard script for Windows/MacOS I'm generating a Cobertura XML and parsing with `ctest_coverage()` this eventually gets the code coverage successfully and prints
```sh
Covered LOC:         4275
Not covered LOC:     7736
Total LOC:           12011
Percentage Coverage: 35.59%
```
But when uploading with `ctest_submit()`, it throws the error above in the title:
```sh
Submit files
   Send to group: Experimental
   SubmitURL: http://.../submit.php?project=...
   Upload file: .../build/Testing/20230428-1929/Configure.xml to http://.../submit.php?project=...&FileName=___Test-Windows___20230428-1929-Experimental___XML___Configure.xml&build=Test-Windows&site=&stamp=20230428-1929-Experimental&MD5=eacd34b0c78d610d105a4229ad6b0caa Size: 1456
   Uploaded: .../build/Testing/20230428-1929/Configure.xml
   Upload file: .../build/Testing/20230428-1929/Build.xml to http://.../submit.php?project=...&FileName=___Test-Windows___20230428-1929-Experimental___XML___Build.xml&build=Test-Windows&site=&stamp=20230428-1929-Experimental&MD5=67f3f9e1b345b477e2982d8e103a1f8b Size: 1051
   Uploaded: .../build/Testing/20230428-1929/Build.xml
   Upload file: .../build/Testing/20230428-1929/Test.xml to http://.../submit.php?project=...&FileName=___Test-Windows___20230428-1929-Experimental___XML___Test.xml&build=Test-Windows&site=&stamp=20230428-1929-Experimental&MD5=2bdfe8cfbeed66ff91f482c672821ac6 Size: 396543
   Uploaded: .../build/Testing/20230428-1929/Test.xml
   Upload file: Coverage.xml to http://.../submit.php?project=...&FileName=___Test-Windows___20230428-1929-Experimental___XML___Coverage.xml&MD5=0ba8793d92dc4400e4c2cae02ed5a845 Size: 60285783
Error parsing XML in stream at line 1: syntax error
   Uploaded: Coverage.xml
   Upload file: .../build/Testing/20230428-1929/CoverageLog-0.xml to http://.../submit.php?project=...&FileName=___Test-Windows___20230428-1929-Experimental___XML___CoverageLog-0.xml&build=Test-Windows&site=&stamp=20230428-1929-Experimental&MD5=e8363868f628e4f1d5837a8f2c1c4134 Size: 961198
   Uploaded: .../build/Testing/20230428-1929/CoverageLog-0.xml
   Upload file: .../build/Testing/20230428-1929/CoverageLog-1.xml to http://.../submit.php?project=...&FileName=___Test-Windows___20230428-1929-Experimental___XML___CoverageLog-1.xml&build=Test-Windows&site=&stamp=20230428-1929-Experimental&MD5=c33a41045efc7e4d861257db1d0ace02 Size: 968575
   Uploaded: .../build/Testing/20230428-1929/CoverageLog-1.xml
   Upload file: .../build/Testing/20230428-1929/CoverageLog-2.xml to http://.../submit.php?project=...&FileName=___Test-Windows___20230428-1929-Experimental___XML___CoverageLog-2.xml&build=Test-Windows&site=&stamp=20230428-1929-Experimental&MD5=880ed998535cb2b31ab2de7337101000 Size: 824903
   Uploaded: .../build/Testing/20230428-1929/CoverageLog-2.xml
   Upload file: .../build/Testing/20230428-1929/Done.xml to http://.../submit.php?project=...&FileName=___Test-Windows___20230428-1929-Experimental___XML___Done.xml&build=Test-Windows&site=&stamp=20230428-1929-Experimental&MD5=d80d8aeff2d497aef8c907aac62aef81 Size: 105
   Uploaded: .../build/Testing/20230428-1929/Done.xml
   Submission successful
```
So every submission is successful except for `Coverage.xml`. This error only happens when it parses with Cobertura XMLs so far in my testing but that's all that we can use at the moment. I'll post the top few lines of the `Coverage.xml` file below:
```sh
<?xml version="1.0" encoding="UTF-8"?>
<Site BuildName="Test-Windows"
	BuildStamp="20230428-1929-Experimental"
	Name="(empty)"
	Generator="ctest-3.25.0-rc4"
	CompilerName=""
	CompilerVersion=""
	OSName="Windows"
	Hostname="..."
	OSRelease=" Professional"
	OSVersion=" (Build 22621)"
	OSPlatform="AMD64"
	Is64Bits="1"
	VendorString="GenuineIntel"
	VendorID="Intel Corporation"
	FamilyID="6"
	ModelID="12"
	ProcessorCacheSize="-1"
	NumberOfLogicalCPU="8"
	NumberOfPhysicalCPU="4"
	TotalVirtualMemory="32475"
	TotalPhysicalMemory="16091"
	LogicalProcessorsPerPhysical="2"
	ProcessorClockFrequency="2611.00"
	>
	<Coverage>
		<StartDateTime>Apr 28 15:30 Eastern Daylight Time</StartDateTime>
		<StartTime>1682710212</StartTime>
		<File Name="....cpp" FullPath="./....cpp" Covered="true">
			<LOCTested>0</LOCTested>
			<LOCUnTested>89</LOCUnTested>
			<PercentCoverage>0.00</PercentCoverage>
			<CoverageMetric>0.10</CoverageMetric>
		</File>
...
```
I'm able to reproduce this same issue on MacOS as well. Any ideas or further logs I can provide?

**Comment by williamjallen** [comment]
What version of CDash are you running?

**Comment by tamuseanmiller** [comment]
> What version of CDash are you running?

The latest currently (3.1.0?)

**Comment by tamuseanmiller** [comment]
Any ideas or more information I can provide here?

**Comment by williamjallen** [comment]
I don't see anything out of the ordinary in the file you provided, but @zackgalbreath probably knows this part of the codebase better than I do.

Things that might be helpful if you're able to provide them:
1. The project name (or at least the characters being used in the project name)
2. A more complete `Coverage.xml`
3. Any relevant CDash log data

**Comment by tamuseanmiller** [comment]
So I'm not seeing any `cdash.log` file in the CDash/backup directory on the server.

**Comment by tamuseanmiller** [comment]
Updated CDash to the most recent version here and am seeing not the same issue but a different one when parsing only the Coverage.xml file that ctest produces.

For whatever reason all of the Coverage-*.xml files parse correctly but specifically the Coverage.xml file doesn't parse correctly in CDash. It does upload successfully now though so that's a plus. Here's a dump of the log it shows when it fails to parse it:
```shell
[2024-08-07 20:55:18] testing.ERROR: error: could not create handler based on xml content {"function":"ctest_parse","build_id":"18"} 
[2024-08-07 20:55:18] testing.WARNING: Failed to process [repo-name]_-__-_1c27de6a-b072-4b99-ad77-8675a97d1ab6_-_f571c2fc27dd575ebce314399ca07c77.xml with message: Symfony\Component\HttpKernel\Exception\HttpException: Could not create handler based on xml content in /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1252
Stack trace:
#0 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(45): Illuminate\Foundation\Application->abort(400, 'Could not creat...', Array)
#1 /cdash/app/cdash/include/ctestparser.php(189): abort(400, 'Could not creat...')
#2 /cdash/app/Jobs/ProcessSubmission.php(195): ctest_parse(Resource id #1197, 1, 'f571c2fc27dd575...')
#3 /cdash/app/Jobs/ProcessSubmission.php(131): App\Jobs\ProcessSubmission->doSubmit('inprogress/secu...', 1, NULL, 'f571c2fc27dd575...', true)
#4 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\ProcessSubmission->handle()
#5 /cdash/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#7 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /cdash/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /cdash/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#10 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ProcessSubmission))
#11 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessSubmission))
#12 /cdash/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /cdash/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ProcessSubmission), false)
#14 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\ProcessSubmission))
#15 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessSubmission))
#16 /cdash/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /cdash/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(App\Jobs\ProcessSubmission))
#18 /cdash/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#19 /cdash/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\Queue\Jobs\Job->fire()
#20 /cdash/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#21 /cdash/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#22 /cdash/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#23 /cdash/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#24 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#25 /cdash/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#27 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#28 /cdash/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#29 /cdash/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call(Array)
#30 /cdash/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /cdash/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 /cdash/vendor/symfony/console/Application.php(1078): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /cdash/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /cdash/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /cdash/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}  
```

I'm going to add, I'm doing this in a really roundabout way due to the limitations of code coverage with MSVC, so this might just be a side effect of how I'm forcing the coverage to be produced but I wanted to note it anyway.

Pinging @zackgalbreath here to see if he has any idea what's going on.
