### ISSUE TITLE
fopen permission error in ctestparser.php (v3.1.0)

### ISSUE THREAD

**Issue by arghdos** [Kitware/CDash#1420]
# Bug report

### Expected Behavior

A successful ctest submission

### Actual Behavior

On the submitting machine, a HTML 500 error is thrown (e.g.:

```
Submit files
   SubmitURL: http://10.194.116.31/cdash/submit.php?project=<MyCoolProject>
   Upload file: /home/arghdos/<MyCoolProject>/configs//Project.xml to http://10.194.116.31/cdash/submit.php?project=<MyCoolProject>&FileName=<Node>___Linux-hiptests-with-hipcc___20230510-0100-Nightly___XML___Project.xml&MD5=a14960f118fc680aaad4c8e3416775ba Size: 459
   Error when uploading file: /home/arghdos/<MyCoolProject>configs//Project.xml
   Error message was: The requested URL returned error: 500
   Problems when submitting via HTTP
```

### CDash Version

3.1.0

### Additional Information

Inspecting the Laravel logs yields more information:

```
May 10 08:34:24 my-cdash-scratch c-dash[201294]: [2023-05-10 13:34:24] development.ERROR: fopen(/home/cdash/CDash/app/cdash/backup/<MyCoolProject>_168372566466.9_Project.xml.lock): failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): fopen(/home/cdash/CDash/app/cdash/backup/<MyCoolProject>_168372566466.9_Project.xml.lock): failed to open stream: Permission denied at /home/cdash/CDash/app/cdash/include/ctestparser.php:103)
May 10 08:34:24 my-cdash-scratch c-dash[201294]: [stacktrace]
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #1 /home/cdash/CDash/app/cdash/include/ctestparser.php(103): fopen()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #2 /home/cdash/CDash/app/cdash/include/ctestparser.php(185): safelyWriteBackupFile()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #3 /home/cdash/CDash/app/cdash/include/ctestparser.php(406): writeBackupFile()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #4 /home/cdash/CDash/app/cdash/include/do_submit.php(144): ctest_parse()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #5 /home/cdash/CDash/app/cdash/public/submit.php(146): do_submit()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #6 /home/cdash/CDash/app/Http/Controllers/CDash.php(164): require('/home/cdash/CDa...')
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #7 /home/cdash/CDash/app/Http/Controllers/CDash.php(220): App\\Http\\Controllers\\CDash->getRequestContents()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #8 /home/cdash/CDash/app/Http/Controllers/CDash.php(59): App\\Http\\Controllers\\CDash->handleSubmission()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #9 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\CDash->__invoke()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #10 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #11 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #12 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #13 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #14 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #15 /home/cdash/CDash/app/Http/Middleware/CheckPassword.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #16 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckPassword->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #17 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #18 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #19 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #20 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #21 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #22 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #23 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #24 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #25 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #26 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #27 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #28 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #29 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #30 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #31 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #32 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #33 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #34 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #35 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #36 /home/cdash/CDash/app/Http/Middleware/CheckDirectoryPermissions.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #37 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDirectoryPermissions->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #38 /home/cdash/CDash/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #39 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #40 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #41 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #42 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #43 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #44 /home/cdash/CDash/app/Http/Middleware/CheckDatabaseConnection.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #45 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDatabaseConnection->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #46 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #47 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #48 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #49 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #50 /home/cdash/CDash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #51 /home/cdash/CDash/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
May 10 08:34:24 my-cdash-scratch c-dash[201294]: #52 {main}
May 10 08:34:24 my-cdash-scratch c-dash[201294]: "}
May 10 08:34:24 my-cdash-scratch c-dash[201294]: 
```

This _seems_ to be an error resulting from trying to get a lock on a backup file: https://github.com/Kitware/CDash/blob/4b1e74921c1f7dd2a13bcde6dfc19614af8e6169/app/cdash/include/ctestparser.php#L103.

It's possible there's a configuration error on my end (e.g., RE: backups), but any hints would be greatly appreciated.

**Comment by arghdos** [comment]
... a few minutes of reading later, I noticed that (somehow, probably from one of my reverts from develop to 3.1.0) some of the folders / files in ~/CDash do not have the right permissions.

Applying:

```
# Modify CDash directory to belong to the www-data group
chgrp -R www-data /path/to/CDash

# Make the CDash directory writeable by group.
chmod -R g+rw /path/to/CDash
```

As discussed in the [install](https://github.com/Kitware/CDash/blob/master/docs/install.md#adjust-filesystem-permissions) resolved the issue.  

A lesson to always RTM
