### ISSUE TITLE
Groups no longer available after trying to add a wildcard group

### ISSUE THREAD

**Issue by vlebourl** [Kitware/CDash#2193]
I added a wildcard group to our cdash dashboard, but something went wrong and now groups are no longer configurable. On the `manageBuildGroup.php` page, my project is not available to select and the page is blank. Meanwhile, the cdash container shows the following: 
```
cdash  | [Fri May 03 06:51:08.639929 2024] [php:notice] [pid 67002] [client 10.10.12.58:49315] [2024-05-03 08:51:08] production.ERROR: Attempt to read property "name" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \\"name\\" on null at /cdash/app/cdash/public/api/v1/manageBuildGroup.php:189)\n[stacktrace]\n#0 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\\\Foundation\\\\Bootstrap\\\\HandleExceptions->handleError(2, 'Attempt to read...', '/cdash/app/cdas...', 189)\n#1 /cdash/app/cdash/public/api/v1/manageBuildGroup.php(189): Illuminate\\\\Foundation\\\\Bootstrap\\\\HandleExceptions->Illuminate\\\\Foundation\\\\Bootstrap\\\\{closure}(2, 'Attempt to read...', '/cdash/app/cdas...', 189)\n#2 /cdash/app/Http/Controllers/CDash.php(99): require('/cdash/app/cdas...')\n#3 /cdash/app/Http/Controllers/CDash.php(117): App\\\\Http\\\\Controllers\\\\CDash->getRequestContents()\n#4 /cdash/app/Http/Controllers/CDash.php(53): App\\\\Http\\\\Controllers\\\\CDash->handleApiRequest()\n#5 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\\\Http\\\\Controllers\\\\CDash->__invoke(Object(Illuminate\\\\Http\\\\Request), 'v1/manageBuildG...')\n#6 /cdash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\\\Routing\\\\Controller->callAction('__invoke', Array)\n#7 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\\\Routing\\\\ControllerDispatcher->dispatch(Object(Illuminate\\\\Routing\\\\Route), Object(App\\\\Http\\\\Controllers\\\\CDash), '__invoke')\n#8 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\\\Routing\\\\Route->runController()\n#9 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\\\Routing\\\\Route->run()\n#10 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\\\Routing\\\\Router->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#11 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#12 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\\\Routing\\\\Middleware\\\\SubstituteBindings->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#13 /cdash/app/Http/Middleware/AuthenticateToken.php(27): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#14 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\\\Http\\\\Middleware\\\\AuthenticateToken->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#15 /cdash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#16 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\\\View\\\\Middleware\\\\ShareErrorsFromSession->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#17 /cdash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#18 /cdash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\\\Session\\\\Middleware\\\\StartSession->handleStatefulRequest(Object(Illuminate\\\\Http\\\\Request), Object(Illuminate\\\\Session\\\\Store), Object(Closure))\n#19 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\\\Session\\\\Middleware\\\\StartSession->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#20 /cdash/app/Http/Middleware/JsonOnly.php(22): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#21 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\\\Http\\\\Middleware\\\\JsonOnly->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#22 /cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#23 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\\\Cookie\\\\Middleware\\\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#24 /cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#25 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\\\Cookie\\\\Middleware\\\\EncryptCookies->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#26 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#27 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\\\Pipeline\\\\Pipeline->then(Object(Closure))\n#28 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\\\Routing\\\\Router->runRouteWithinStack(Object(Illuminate\\\\Routing\\\\Route), Object(Illuminate\\\\Http\\\\Request))\n#29 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\\\Routing\\\\Router->runRoute(Object(Illuminate\\\\Http\\\\Request), Object(Illuminate\\\\Routing\\\\Route))\n#30 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\\\Routing\\\\Router->dispatchToRoute(Object(Illuminate\\\\Http\\\\Request))\n#31 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\\\Routing\\\\Router->dispatch(Object(Illuminate\\\\Http\\\\Request))\n#32 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\\\Foundation\\\\Http\\\\Kernel->Illuminate\\\\Foundation\\\\Http\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#33 /cdash/app/Http/Middleware/Timer.php(18): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#34 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\\\Http\\\\Middleware\\\\Timer->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#35 /cdash/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#36 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\\\Http\\\\Middleware\\\\TrustProxies->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#37 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#38 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\\\Foundation\\\\Http\\\\Middleware\\\\TransformsRequest->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#39 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\\\Foundation\\\\Http\\\\Middleware\\\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\n#40 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\n#41 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\\\Foundation\\\\Http\\\\Middleware\\\\TransformsRequest->handle(Object(Illuminate
dle(Object(Illuminate
cdash  | 10.10.12.58 - - [03/May/2024:06:51:08 +0000] "GET /api/v1/manageBuildGroup.php?projectid=1 HTTP/1.1" 500 814 "https://cdash.hostname.com/manageBuildGroup.php?projectid=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
``` 

Any idea what happened and how to salvage that? 

Thanks a lot

We are on:
CDash v3.3.0 via docker.

**Comment by williamjallen** [comment]
@vlebourl Thanks for this bug report!  #2194 will be included in 3.4, which we plan to release in the next week or so.
