### ISSUE TITLE
CDash 3.4 - 3.7 submission error

### ISSUE THREAD

**Issue by ngladitz** [Kitware/CDash#2208]
# Bug report

### Expected Behavior

No submission error.

### Actual Behavior

Submission error.

### CDash Version

3.4

### Additional Information

I've got a submission that has failed with:
```
2024-05-16T13:00:31.312699Z 01O {"status":1,"description":"SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"type\" of relation \"configureerrordiff\" violates not-null constraint\nDETAIL:  Failing row contains (281424, null, 1). (Connection: pgsql, SQL: insert into \"configureerrordiff\" (\"buildid\", \"difference\") values (281424, 1) on conflict do nothing)"}
```

I don't know how to reproduce the issue. I repeated my failing CI job and this time the submission went through without error.

**Comment by ngladitz** [comment]
Still seeing this with 3.7.0; seems to happen sporadically:
```
Next Illuminate\Database\QueryException: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "type" of relation "configureerrordiff" violates not-null constraint
DETAIL:  Failing row contains (319455, null, 1). (Connection: pgsql, SQL: insert into "configureerrordiff" ("buildid", "difference") values (319455, 1) on conflict do nothing) in /opt/CDash/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
Stack trace:
#0 /opt/CDash/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/CDash/vendor/laravel/framework/src/Illuminate/Database/Connection.php(600): Illuminate\Database\Connection->run()
#2 /opt/CDash/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3528): Illuminate\Database\Connection->affectingStatement()
#3 /opt/CDash/app/cdash/app/Model/Build.php(1209): Illuminate\Database\Query\Builder->insertOrIgnore()
#4 /opt/CDash/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): CDash\Model\Build->CDash\Model\{closure}()
#5 /opt/CDash/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(509): Illuminate\Database\Connection->transaction()
#6 /opt/CDash/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\Database\DatabaseManager->__call()
#7 /opt/CDash/app/cdash/app/Model/Build.php(1188): Illuminate\Support\Facades\Facade::__callStatic()
#8 /opt/CDash/app/cdash/xml_handlers/configure_handler.php(229): CDash\Model\Build->ComputeConfigureDifferences()
#9 [internal function]: ConfigureHandler->endElement()
#10 /opt/CDash/app/cdash/include/ctestparser.php(235): xml_parse()
#11 /opt/CDash/app/Jobs/ProcessSubmission.php(207): ctest_parse()
...
```

**Comment by ngladitz** [comment]
Found database/migrations/2019_09_30_111055_create_configureerrordiff_table.php which seems to say "type" and "difference" are supposed to be nullable. Adjusted my schema manually hoping this will fix the issue.
Not sure how I got into this state 😄

**Comment by ngladitz** [comment]
Found database/migrations/2019_09_30_111055_create_configureerrordiff_table.php which seems to say "type" and "difference" are supposed to be nullable. Adjusted my schema manually hoping this will fix the issue.
Not sure how I got into this state 😄
