### ISSUE TITLE
there are many this deployment error:.ERROR: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by bonniechen1119** [Kitware/CDash#2510]
# Bug report
there are many this deployment error:.ERROR: Deadlock found when trying to get lock; try restarting transaction
### Expected Behavior

if when cdash auto remove record, it meet some error
### Actual Behavior
[2024-10-22 02:19:11] development.ERROR: Deadlock found when trying to get lock; try restarting transaction
#0 /home/kitware/cdash/app/cdash/include/CDash/Database.php(114): CDash\Database->logPdoError(Array)
#1 /home/kitware/cdash/app/cdash/include/pdo.php(279): CDash\Database->query('DELETE FROM bui...')
#2 /home/kitware/cdash/app/cdash/app/Model/BuildUpdate.php(93): pdo_query('DELETE FROM bui...')
#3 /home/kitware/cdash/app/cdash/xml_handlers/update_handler.php(134): CDash\Model\BuildUpdate->Insert()
#4 [internal function]: UpdateHandler->endElement(Resource id #510, 'UPDATE')
#5 /home/kitware/cdash/app/cdash/include/ctestparser.php(363): xml_parse(Resource id #510, '<?xml version="...', false)
#6 /home/kitware/cdash/app/cdash/include/do_submit.php(143): ctest_parse(Resource id #507, '1', '1223339', '1c111dff315b5b9...', true)
#7 /home/kitware/cdash/app/cdash/public/submit.php(146): do_submit(Resource id #507, '1', '1223339', '1c111dff315b5b9...', true)
#8 /home/kitware/cdash/app/Http/Controllers/CDash.php(161): require('/home/kitware/c...')
#9 /home/kitware/cdash/app/Http/Controllers/CDash.php(217): App\Http\Controllers\CDash->getRequestContents()
#10 /home/kitware/cdash/app/Http/Controllers/CDash.php(56): App\Http\Controllers\CDash->handleSubmission()
#11 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\CDash->__invoke('submit.php')
#12 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('__invoke', Array)
#13 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\CDash), '__invoke')
#14 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#15 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#16 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/kitware/cdash/app/Http/Middleware/CheckPassword.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckPassword->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#34 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#35 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /home/kitware/cdash/app/Http/Middleware/CheckDirectoryPermissions.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckDirectoryPermissions->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/kitware/cdash/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/kitware/cdash/app/Http/Middleware/CheckDatabaseConnection.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckDatabaseConnection->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 /home/kitware/cdash/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main} {"function":"logPdoError","build_id":"1223339"}

### CDash Version
v3.0.3

**Comment by williamjallen** [comment]
A substantial amount of code has changed since CDash 3.0.3 and we haven't gotten any other similar reports.  Please file a new issue if you're still experiencing issues with CDash 4.0+.
