### ISSUE TITLE
Email notifications failing from workers

### ISSUE THREAD

**Issue by wmason-lanl** [Kitware/CDash#2618]
CDash v3.6.2

Email notifications are failing to send because they are defaulting to sendmail even though MAIL_MAILER is set to "smtp".

[2024-12-09 18:45:18] production.INFO: Connection to "process /usr/sbin/sendmail -bs" has been closed unexpectedly.  
[2024-12-09 18:45:18] production.INFO: [SENT] EmailMessage titled, 'FAILED (m=1): <redacted>
[2024-12-09 18:46:36] production.INFO: Connection to "process /usr/sbin/sendmail -bs" has been closed unexpectedly.  
[2024-12-09 18:46:36] production.INFO: [SENT] EmailMessage titled, 'FAILED (t=1): <redacted>

Here are the MAIL options I have set:

MAIL_MAILER=smtp
MAIL_HOST=mymailer.domain
MAIL_PORT=25
MAIL_FROM_ADDRESS=<from address>
MAIL_FROM_NAME=<from name>
MAIL_REPLY_ADDRESS=<from address>

Please let me know if I can provide any additional information.

**Comment by fspindle** [comment]
It doesn't fix the issue for me!
My server version is v3.6.2-84-gb041feb96

If I put one of the following lines:
```
#MAIL_ENCRYPTION=null
or MAIL_ENCRYPTION=null
or MAIL_ENCRYPTION=tls
or MAIL_ENCRYPTION=starttls
```
When I submit a test to the server, I get the following error message:
```
% ctest -D ExperimentalSubmit
   Site: MAC-03220146
   Build name: Darwin-amd64
Submit files
   Send to group: Experimental
   SubmitURL: https://server/submit.php?project=myproject
   Uploaded: /Users/my/build/Testing/20241217-0737/Configure.xml
   Server Response:
{"status":1,"description":"Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:0A000086:SSL routines::certificate verify failed"}
   Submit failed, waiting 5 seconds...
```

In the docker container, the logs are:
```
[2024-12-17 07:38:02] production.WARNING: Failed to process a98f993e29bff795ebbbeee1d4b6f.xml with message: Symfony\Component\Mailer\Exception\TransportException: Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000086:SSL routines::certificate verify failed in /cdash/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:171
Stack trace:
#0 [internal function]: Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream->Symfony\Component\Mailer\Transport\Smtp\Stream\{closure}(2, 'stream_socket_e...', '/cdash/vendor/s...', 174)
#1 /cdash/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php(174): stream_socket_enable_crypto(Resource id #14, true)
#2 /cdash/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php(152): Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream->startTLS()
#3 /cdash/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php(118): Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport->doEhloCommand()
#4 /cdash/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(254): Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport->executeCommand('HELO [127.0.0.1...', Array)
#5 /cdash/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(277): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doHeloCommand()
#6 /cdash/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(209): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->start()
#7 /cdash/vendor/symfony/mailer/Transport/AbstractTransport.php(69): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doSend(Object(Symfony\Component\Mailer\SentMessage))
#8 /cdash/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(137): Symfony\Component\Mailer\Transport\AbstractTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#9 /cdash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(573): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#10 /cdash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(335): Illuminate\Mail\Mailer->sendSymfonyMessage(Object(Symfony\Component\Mime\Email))
#11 /cdash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(224): Illuminate\Mail\Mailer->send(NULL, Array, Object(Closure))
#12 /cdash/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(592): Illuminate\Mail\Mailer->raw('A submission to...', Object(Closure))
#13 /cdash/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\Mail\MailManager->__call('raw', Array)
#14 /cdash/app/cdash/include/cdashmail.php(33): Illuminate\Support\Facades\Facade::__callStatic('raw', Array)
#15 /cdash/app/cdash/include/Messaging/Notification/Email/Mail.php(39): cdashmail('my.name...', 'FAILED (b=4, w=...', 'A submission to...')
#16 /cdash/app/cdash/include/Messaging/Notification/Mailer.php(50): CDash\Messaging\Notification\Email\Mail->send(Object(CDash\Messaging\Notification\Email\EmailMessage))
#17 /cdash/app/cdash/include/Messaging/Notification/Mailer.php(38): CDash\Messaging\Notification\Mailer->sendNotification(Object(CDash\Messaging\Notification\Email\EmailMessage))
#18 /cdash/app/cdash/include/sendemail.php(616): CDash\Messaging\Notification\Mailer::send(Object(CDash\Messaging\Notification\NotificationCollection))
#19 /cdash/app/Jobs/ProcessSubmission.php(238): sendemail(Object(BuildHandler), 1)
#20 /cdash/app/Jobs/ProcessSubmission.php(137): App\Jobs\ProcessSubmission->doSubmit('inprogress/myproject...', 1, 134195, 'ed1a98f993e29bf...', true)
#21 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\ProcessSubmission->handle()
#22 /cdash/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#24 /cdash/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 /cdash/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 /cdash/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#27 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ProcessSubmission))
#28 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessSubmission))
#29 /cdash/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /cdash/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ProcessSubmission), false)
#31 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\ProcessSubmission))
#32 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessSubmission))
#33 /cdash/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /cdash/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\SyncJob), Object(App\Jobs\ProcessSubmission))
#35 /cdash/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#36 /cdash/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#37 /cdash/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(254): Illuminate\Queue\SyncQueue->push(Object(App\Jobs\ProcessSubmission))
#38 /cdash/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(230): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(App\Jobs\ProcessSubmission))
#39 /cdash/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(App\Jobs\ProcessSubmission))
#40 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\Bus\Dispatcher->dispatch(Object(App\Jobs\ProcessSubmission))
#41 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(19): Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#42 /cdash/app/Http/Controllers/SubmissionController.php(163): App\Jobs\ProcessSubmission::dispatch('myproject_-__-_655eb...', 1, 134195, 'ed1a98f993e29bf...')
#43 /cdash/app/Http/Controllers/SubmissionController.php(45): App\Http\Controllers\SubmissionController->submitProcess()
#44 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\SubmissionController->submit()
#45 /cdash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('submit', Array)
#46 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\SubmissionController), 'submit')
#47 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#48 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route->run()
#49 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /cdash/app/Http/Middleware/PasswordExpired.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\PasswordExpired->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /cdash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#65 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#66 /cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#67 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#68 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#69 /cdash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /cdash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#71 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /cdash/app/Http/Middleware/Timer.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\Timer->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /cdash/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#81 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#84 /cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#86 /cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#87 /cdash/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#88 {main}
```
```

**Comment by fspindle** [comment]
Moreover when I set `sendmail`instead of `smtp`
```
MAIL_MAILER=sendmail
MAIL_HOST=mymailer.domain
MAIL_PORT=25
MAIL_FROM_ADDRESS=admin-cdash@domain
MAIL_FROM_NAME=CDash
MAIL_REPLY_ADDRESS=noreply@domain
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```
I have the following issue
```
[2024-12-17 09:43:55] production.WARNING: Failed to process ViSP_-__-_41892047-94e0-4811-b810-a9a2f2508f56_-_21d3c237e12707853c220569eb4a33f9.xml with message: Symfony\Component\Mailer\Exception\TransportException: Connection to "process /usr/sbin/sendmail -bs -i" has been closed unexpectedly. in /cdash/vendor/symfony/mailer/Transport/Smtp/Stream/AbstractStream.php:88
Stack trace:
#0 /cdash/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(346): Symfony\Component\Mailer\Transport\Smtp\Stream\AbstractStream->readLine()
#1 /cdash/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(276): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->getFullResponse()
#2 /cdash/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(209): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->start()
#3 /cdash/vendor/symfony/mailer/Transport/AbstractTransport.php(69): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doSend(Object(Symfony\Component\Mailer\SentMessage))
#4 /cdash/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(137): Symfony\Component\Mailer\Transport\AbstractTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#5 /cdash/vendor/symfony/mailer/Transport/SendmailTransport.php(75): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#6 /cdash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(573): Symfony\Component\Mailer\Transport\SendmailTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#7 /cdash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(335): Illuminate\Mail\Mailer->sendSymfonyMessage(Object(Symfony\Component\Mime\Email))
#8 /cdash/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(224): Illuminate\Mail\Mailer->send(NULL, Array, Object(Closure))
#9 /cdash/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(592): Illuminate\Mail\Mailer->raw('A submission to...', Object(Closure))
#10 /cdash/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\Mail\MailManager->__call('raw', Array)
#11 /cdash/app/cdash/include/cdashmail.php(33): Illuminate\Support\Facades\Facade::__callStatic('raw', Array)
#12 /cdash/app/cdash/include/Messaging/Notification/Email/Mail.php(39): cdashmail('my.name...', 'FAILED (b=4, w=...', 'A submission to...')

```
